<?php 
defined('BASEPATH') OR exit('No direct script access allowed');

$config = array(
    "default" => array(
    	"v_user_applicant.user_id" => "user_id", 
		"v_user_applicant.role_code" => "role_code", 
		'v_user_applicant.institution' => 'institution',
		"v_user_applicant.group_id" => "group_id", 
		"v_user_applicant.username" => "username", 
		"v_user_applicant.email" => "email", 
		"v_user_applicant.first_name" => "first_name", 
		"v_user_applicant.contact" => "contact", 
		"v_user_applicant.gender_code" => "gender_code", 
		"v_user_applicant.nik" => "nik", 
		"v_user_applicant.npwp" => "npwp",
		"v_user_applicant.tuk_id" => "tuk_id",
		"v_user_applicant.tuk_name" => "tuk_name",
		"v_user_applicant.schedule_assessment_id" => "schedule_assessment_id",
        "v_user_applicant.jobs_code" => "jobs_code",
		"v_user_applicant.jobs_name" => "jobs_name",
		"v_user_applicant.religion" => "religion",
		"v_user_applicant.picture" => "picture",
		"v_user_applicant.signature" => "signature"
	),
	"optional" => array(
		// "v_user_applicant.tuk_name" => "tuk_name",
		"v_user_applicant.nomor_skema" => "nomor_skema",
		"v_user_applicant.tujuan_assessment" => "tujuan_assessment",
		"v_user_applicant.kebangsaan" => "kebangsaan",
		"v_user_applicant.kode_pos" => "kode_pos",
		"v_user_applicant.telepon_rumah" => "telepon_rumah",
		"v_user_applicant.telepon_kantor" => "telepon_kantor",
		"v_user_applicant.nama_lembaga" => "nama_lembaga",
		"v_user_applicant.jabatan" => "jabatan",
		"v_user_applicant.alamat_pekerjaan" => "alamat_pekerjaan",
		"v_user_applicant.kode_pos_pekerjaan" => "kode_pos_pekerjaan",
		"v_user_applicant.telepon_pekerjaan" => "telepon_pekerjaan",
		"v_user_applicant.fax_pekerjaan" => "fax_pekerjaan",
		"v_user_applicant.email_pekerjaan" => "email_pekerjaan",
		"v_user_applicant.address" => "address",
		"v_user_applicant.last_name" => "last_name", 
		"v_user_applicant.nik_photo" => "nik_photo",
		"v_user_applicant.npwp_photo" => "npwp_photo",
		"v_user_applicant.pendidikan_terakhir" => "pendidikan_terakhir",
		"v_user_applicant.last_education_certificate_photo" => "last_education_certificate_photo",
		"v_user_applicant.training_certificate_photo" => "training_certificate_photo",
		"v_user_applicant.colored_photo" => "colored_photo",
		"v_user_applicant.family_card_photo" => "family_card_photo",
		"v_user_applicant.place_of_birth" => "place_of_birth",
		"v_user_applicant.date_of_birth" => "date_of_birth",
		"v_user_applicant.last_login" => "last_login", 
		"v_user_applicant.created_by" => "created_by", 
		"v_user_applicant.modified_by" => "modified_by", 
		"v_user_applicant.created_date" => "created_date", 
		"v_user_applicant.modified_date" => "modified_date",
		"v_user_applicant.signature_flag" => "signature_flag"
	)
);